apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::058264293850:role/new-github-ci
      username: new-github-ci
      groups:
      - system:masters
    - userarn: arn:aws:iam::058264293850:user/github-ci
      username: github-ci
      groups:
      - system:masters
